options:
	skill_name: "テスト"
	skill_type: "戦士"
	mp: 10
	cool_time: 10 seconds

on load:
	registerSkill({@skill_name},{@skill_type})

function ForceTest(p: player, type: text):
	set {_uuid} to uuid of {_p}
	if {player.%{_type}%.skill::%{_uuid}%} is {@skill_name}:
		if difference between {player.%{_type}%.cooldown::%{_uuid}%} and now >= {@cool_time}:
			if {@skill_type} contains {player.job::%{_uuid}%}:
				if {player.nowmp::%{_uuid}%} >= {@mp}:
					subtract {@mp} from {player.nowmp::%{_uuid}%}
					set {player.%{_type}%.cooldown::%{_uuid}%} to now
					send "Test" to {_p}
				else:
					send "&c&lMPが足りません..." to {_p}
			else:
				send "&c&l現在の職業ではこのスキルを使用できません" to {_p}
		else:
			set {_d} to difference between {player.%{_type}%.cooldown::%{_uuid}%} and now
			set {player.skill.cooldown::%{_uuid}%} to 10
			play "BLOCK_NOTE_BLOCK_BASS" to {_p} at volume 2

on offhand switch:
	ForceTest(player,"mobile")

on right click:
	if player is sneaking:
		ForceTest(player,"common1")
on drop:
	if player is sneaking:
		ForceTest(player,"common2")
	else:
		ForceTest(player,"common3")